engines:
  haxe-checkstyle:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
      MD029:
        style: "ordered"
ratings:
  paths:
    - "**.hx"
    - "**.md"
