version: "{build}"

clone_folder: C:\projects\hxWidgets

clone_depth: 1

environment:
    global:
        HXCPP_ROOT: C:\projects\hxcpp
        HAXELIB_ROOT: C:\projects\haxelib
        WXWIDGETS_ROOT: C:\projects\wxWidgets

cache:
    - wxWidgets-3.0.2.7z -> appveyor.yml
    - wxMSW-3.0.2_vc120_x64_Dev.7z -> appveyor.yml

install:
    # Install haxe, download the chocolatey package
    - cinst haxe -y
    - RefreshEnv
    - haxe -version
    - neko -version
    # Setup haxe
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"
    # Download dev hxcpp
    - git clone --recursive --depth 1 -q https://github.com/HaxeFoundation/hxcpp.git %HXCPP_ROOT%
    - haxelib dev hxcpp %HXCPP_ROOT%
    # Build dev hxcpp
    - cd %HXCPP_ROOT%\tools\hxcpp
    - haxe compile.hxml
    - cd %HXCPP_ROOT%\tools\build
    - haxe compile.hxml
    - cd %HXCPP_ROOT%\project
    - neko build.n clean
    - neko build.n windows-x86
    # Download wxWidgets
    - curl -fsS -o wxWidgets-3.0.2.7z --retry 3 https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.2/wxWidgets-3.0.2.7z
    - curl -fsS -o wxMSW-3.0.2_vc120_x64_Dev.7z --retry 3 https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.2/wxMSW-3.0.2_vc120_x64_Dev.7z
    # Install wxWidgets
    - 7z e wxWidgets-3.0.2.7z -o%WXWIDGETS_ROOT% * -r
    - 7z e wxMSW-3.0.2_vc120_x64_Dev.7z -o%WXWIDGETS_ROOT% * -r
    - mv %WXWIDGETS_ROOT%\lib\vc120_x64_dll %WXWIDGETS_ROOT%\lib\vc_dll
    - SET WXWIN=%WXWIDGETS_ROOT%

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%\samples\00-Showcase
    - haxe build.hxml
